### ISSUE TITLE
Confusing Asterisk

### ISSUE THREAD

**Issue by maxoakland** [marcrobledo/super-game-boy-border-converter#1]
There's an asterisk next to 4 Palettes and there is only one other asterisk on the page, under Download SGB File. I don't believe these are connected. I'm not sure what the 4 Palette asterisk means

![image](https://github.com/marcrobledo/super-game-boy-border-converter/assets/57502156/6fc0f986-8720-44cc-b230-1419f77cedc3)

My suggestion to fix the issue: Put some text underneath the Palettes box to explain what happens if you choose 4 palettes. Remove the asterisk in front of (all data in a single file) because the parenthesis are good enough to explain. Another alternative would be put a (?) help button next to the Palettes popup and if the user clicks on it, an explanation comes up

**Comment by marcrobledo** [comment]
You are right, thank you!
I've removed the 4 palettes option, since it's confusing and I don't think it's useful (since it makes the border only compatible for some inaccurate emulators).

**Comment by maxoakland** [comment]
> You are right, thank you! I've removed the 4 palettes option, since it's confusing and I don't think it's useful (since it makes the border only compatible for some inaccurate emulators).

That's interesting! Would love a technical explanation if you have time

**Comment by marcrobledo** [comment]
Sure!
The SNES has 8 palettes of 16 colors.
The SGB uses the first four palettes for the game screen and, theorically, the last four are for the border. So, in theory, you could use 4 palettes for the border.

However, the official SGB development guidelines say only three palettes are available. And it's true, because if you build a border made of four palettes and run the game in real hardware, the tiles using the fourth palette will show up incorrectly. That's due to the latest palette being used for the SGB menu (the one that opens with L+R).

It's needed to clarify that **GB emulators are not emulating SGB features**. In order to emulate the SGB accurately you need an SNES emulator that is capable of emulating also SGB. And there is only one around that does it: bsnes, also known as higan.
The GB emulators just capture the VRAM transfers and **simulate** the border and palettes. That's it. They are not emulating the rest of SGB features that require the SNES hardware (sound chip, multiplayer and even SNES code execution [Space Invaders]), because they are not SNES emulators after all. For that reason, some GB emulators are not taking into account the fourth reserved palette and show the 4 palettes borders correctly.

I removed the option of four palettes because it's not a good idea to leave around a tool that is able to build ROM hacks that would only play correctly in a few specific inaccurate emulators.

**Comment by maxoakland** [comment]
> Sure! The SNES has 8 palettes of 16 colors. The SGB uses the first four palettes for the game screen and, theorically, the last four are for the border. So, in theory, you could use 4 palettes for the border.
> 
> However, the official SGB development guidelines say only three palettes are available. And it's true, because if you build a border made of four palettes and run the game in real hardware, the tiles using the fourth palette will show up incorrectly. That's due to the latest palette being used for the SGB menu (the one that opens with L+R).
> 
> It's needed to clarify that **GB emulators are not emulating SGB features**. In order to emulate the SGB accurately you need an SNES emulator that is capable of emulating also SGB. And there is only one around that does it: bsnes, also known as higan. The GB emulators just capture the VRAM transfers and **simulate** the border and palettes. That's it. They are not emulating the rest of SGB features that require the SNES hardware (sound chip, multiplayer and even SNES code execution [Space Invaders]), because they are not SNES emulators after all. For that reason, some GB emulators are not taking into account the fourth reserved palette and show the 4 palettes borders correctly.
> 
> I removed the option of four palettes because it's not a good idea to leave around a tool that is able to build ROM hacks that would only play correctly in a few specific inaccurate emulators.

Thanks for explaining!
